import { TCeleb } from "@/components/Categories/CelebrityCards";

import img1 from "../assets/image 13.png";
import sunny from "../assets/image 12.png";
import mun from "../assets/image 14.png";
import dilip from "../assets/image 15.png";

export const data: TCeleb[] = [
  {
    _id: 1,
    name: "Shankar Mahadevan",
    img: img1,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: true,
  },
  {
    _id: 2,
    name: "Sunny Deol",
    img: sunny,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: true,
  },
  {
    _id: 3,
    name: "Shankar Mahadevan",
    img: img1,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: true,
  },
  {
    _id: 4,
    name: "Shankar Mahadevan",
    img: img1,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: true,
  },
  {
    _id: 5,
    name: "Sunny Deol",
    img: sunny,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: true,
  },
  {
    _id: 6,
    name: "Shankar Mahadevan",
    img: img1,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: true,
  },
  {
    _id: 7,
    name: "Sunny Deol",
    img: sunny,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: true,
  },
  {
    _id: 8,
    name: "Munmun Datta",
    img: mun,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
  {
    _id: 9,
    name: "Dilip Joshi",
    img: dilip,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
  {
    _id: 10,
    name: "Munmun Datta",
    img: mun,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
  {
    _id: 11,
    name: "Dilip Joshi",
    img: dilip,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
  {
    _id: 12,
    name: "Munmun Datta",
    img: mun,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
  {
    _id: 13,
    name: "Dilip Joshi",
    img: dilip,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
  {
    _id: 14,
    name: "Munmun Datta",
    img: mun,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
  {
    _id: 15,
    name: "Dilip Joshi",
    img: dilip,
    tags: ["Movie Star", "Baby Doll"],
    price: 9999,
    available: false,
  },
];

// export const data2 = [
//   {
//     _id: 1,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 2,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 3,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 4,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 5,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 6,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 7,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 8,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
//   {
//     _id: 9,
//     name: "Chota Bheem",
//     img: img1,
//     tags: ["Tv Star", "Common Character"],
//     price: 9999,
//     recentlyViewed: true,
//   },
// ];
